newPassword: "新密码"
accountFilePath: "账号密码信息所在txt的文件路径(注意,需要使用'双杠'而不是'单杠')"
browser: "edge或者chrome(根据自己浏览器以及webdriver选择)"
webDriverPath: "webdriver.exe的文件路径(注意,需要使用'双杠'而不是'单杠')"
imapServer: "qq邮箱为imap.qq.com,具体请查看主页教程"
imapUsername: "账号已验证的邮箱账号"
imapPassword: "邮箱密码或是邮箱登陆码,具体请查看主页教程"
