newPassword: "新密码"
accountFilePath: "账号密码信息所在txt的文件路径(注意,需要使用'双杠'而不是'单杠')"
accountDelimiter: "账密文件中的分隔符,默认为----,如有需要请自行修改"
browser: "edge或者chrome(根据自己浏览器以及webdriver选择)"
imapServer: "(此4项若不需要邮箱验证请置为空即可)qq邮箱为imap.qq.com,具体请查看主页教程"
imapUsername: "(此4项若不需要邮箱验证请置为空即可)账号已验证的邮箱账号"
imapPassword: "(此4项若不需要邮箱验证请置为空即可)邮箱密码或是邮箱登陆码,具体请查看主页教程"
imapDelay: "(此4项若不需要邮箱验证请置为空即可)获取邮箱验证延迟,单位为秒,默认为10秒"
