language: "zh_CN或者en_US或者zh_TW"
newPassword: "新密码"  # 留空将自动产生随机密码
accountFilePath: "账号密码文件路径"
accountDelimiter: "----"
browser: "chrome"
# 更多配置请参考github中readme文件(For more configuration, please refer to the github readme file)
# 请我喝杯咖啡吧~ https://github.com/Yudaotor
